### ISSUE TITLE
How do you add this to Xamarin Studio?

### ISSUE THREAD

**Issue by jchannon** [xunit/xamarinstudio.xunit#1]
I'd like to use this in XS, is there a installation package available?

**Comment by x2bool** [comment]
I will publish the package soon. If everything goes well, you should see the addin at the official Xamarin Studio repository tomorrow.

**Comment by jchannon** [comment]
Brill! Thanks

**Comment by jchannon** [comment]
Please let me know when its up!

**Comment by x2bool** [comment]
It is already (at least 12 hours). Can you see the addin in the repo?

**Comment by jchannon** [comment]
No, do I need to add a new repository?
![screen shot 2015-03-10 at 10 18 33](https://cloud.githubusercontent.com/assets/105126/6573028/e95b6864-c70e-11e4-822b-b583859f2693.png)

**Comment by x2bool** [comment]
![screen shot 2015-03-10 at 14 45 00](https://cloud.githubusercontent.com/assets/892945/6575023/e8513b92-c73b-11e4-8c21-df9585e10cd3.png)

Make sure you have clicked the "Refresh" button. Also you could install the addin manually. Download here: http://addins.monodevelop.com/Project/Index/160

**Comment by jchannon** [comment]
Got it working! Thanks. Will try and help get run tests per class, per test added!
