### ISSUE TITLE
Run Tests per Class

### ISSUE THREAD

**Issue by jchannon** [xunit/xamarinstudio.xunit#2]
Have the ability to run all tests in a class

**Comment by x2bool** [comment]
???
You should be able to run all tests in a class as well as individual tests. For me debugging also works.
![screen shot 2015-03-10 at 17 33 24](https://cloud.githubusercontent.com/assets/892945/6576983/c90f926e-c74b-11e4-9416-889bed00c911.png)

**Comment by jchannon** [comment]
Ah I didnt see that UI, I only saw the Test Results pane. This is great thanks!

I just tried debug but it doesnt seem to see local variables in the test

![screen shot 2015-03-10 at 14 41 10](https://cloud.githubusercontent.com/assets/105126/6577141/9e24d4dc-c733-11e4-951c-5929711f38da.png)

**Comment by x2bool** [comment]
For some reason Xamarin Studio's maintainers removed the "Run" and "Debug" buttons some time ago. So yeah, today the right click menu is the only way.

**Comment by jchannon** [comment]
Right click is fine, any ideas why the debugging doesnt seem to work?

**Comment by x2bool** [comment]
Seems like a debugger issue to me! The addin has very little to do with the debugger. But I am not sure!
