### ISSUE TITLE
Avoid duplicate items in Add-in Manager

### ISSUE THREAD

**Issue by lextm** [xunit/xamarinstudio.xunit#20]
The [original add-in](http://addins.monodevelop.com/Project/Index/160) is still alive and keeps publishing.

We might stop it in favor of [the new entry](http://addins.monodevelop.com/Project/Index/220).

**Comment by lextm** [comment]
@x2bool do you think we can stop the original entry?

**Comment by x2bool** [comment]
I don't know how to signin to the site. I used an Open ID account to publish the addin. Open ID for this account doesn't seem to work for me anymore. So I think that our best bet is to write to Xamarin and ask for manual removal. Any ideas how to contact them?

**Comment by lextm** [comment]
Hi, leave that to me. I will contact them and update here.

**Comment by lextm** [comment]
Xamarin has just pushed 6.0 to stable channel, so expect developers migrate to that version. The good news is that once all developers move, then they only see the new add-in in Add-in Manager.

Close this issue now as resolved.
