### ISSUE TITLE
Downloaded mpack of xUnit2 addin 0.5.3 not working with MonoDevelop 5.10 anymore

### ISSUE THREAD

**Issue by bpiepiora** [xunit/xamarinstudio.xunit#28]
Hi!

The download of the xUnit addin 0.5.3 (Stable) under http://addins.monodevelop.com/Project/Index/220 points to the wrong version (0.6.5). Currently it's impossible to get the xUnit2 addin running under MonoDevelop 5.10.

**Comment by lextm** [comment]
Can you use Add-in Manager of MonoDevelop to install then? I will see into it tonight.

**Comment by bpiepiora** [comment]
No, that doesn't work either. The Add-In Manager also installs the version for MonoDevelop 6 which cannot be loaded.

**Comment by lextm** [comment]
I just published 0.5.4 and tested the steps.

It seems that Add-in Manager always shows 0.6.5 right now, which is wrong.

You have to manually download the mpack file for 0.5.4, and install from that file. I have tested and it works on my Ubuntu.

**Comment by bpiepiora** [comment]
It works now, thank you!

**Comment by bpiepiora** [comment]
Sorry! I have a problem executing the tests. With the activated 0.5.4 Add-In MonoDevelop shuts down with a fatal error, when I right click on the Test project in the Solution Explorer.

**Comment by lextm** [comment]
@bpiepiora That sounds like another issue. Can you create a new issue and paste more details (especially a step by step guide for me to reproduce it)? Launch MonoDevelop at terminal and then reproduce the issue, so that at terminal you might see more info about the crash.

I tested with https://github.com/lextm/obfuscar, which has many test cases, but could not reproduce the fatal error you mentioned.

**Comment by bpiepiora** [comment]
Okay, I found the problem. There was a project reference to an older xUnit beta version aside the current version in my C# project file. After removing this reference the fatal error didn't popup again.

btw: interesting obfuscator project ;)

**Comment by lextm** [comment]
Great. Thanks for sharing the solution as it might help others out.
