### ISSUE TITLE
Xamarin Studio 6.0.1 Support

### ISSUE THREAD

**Issue by jasontseu1983** [xunit/xamarinstudio.xunit#29]
Currently the addin is not loaded with the latest Xamarin Studio version 6.0.1.

**Comment by lextm** [comment]
Thanks. Many other add-in suffers the same issue and I am hoping Xamarinti solve that instead of us.

**Comment by lextm** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=42089

Xamarin tracks this issue here.

**Comment by jasontseu1983** [comment]
Issue closed.

I also verified latest fix 6.0.1.9 too
