### ISSUE TITLE
Addin called 'Dumb addin' within Xamarin Studio

### ISSUE THREAD

**Issue by brandonrisell** [xunit/xamarinstudio.xunit#51]
This threw me off, but when I search for this addin within Xamarin Studio or even manually download and install it, it is referenced as the `Dumb addin`. I searched this github repo and see no reference to the word Dumb. Is this intentional?

XS Version: 6.1.2 (Build 44)
xUnit addin version: 0.6.99

**Comment by brandonrisell** [comment]
<img width="641" alt="screen shot 2016-12-12 at 10 38 37 am" src="https://cloud.githubusercontent.com/assets/1037386/21111622/34ad2bb6-c057-11e6-9143-936756ff8176.png">

**Comment by lextm** [comment]
That's just the dumb one.

This add-in should be downloaded from http://addins.monodevelop.com/Project/Index/220

**Comment by brandonrisell** [comment]
I did download and install from there, that's what the screenshot above is of. I uninstalled, restarted, and then tried downloading and installing from that link just now to verify.
<img width="293" alt="screen shot 2016-12-13 at 11 27 49 am" src="https://cloud.githubusercontent.com/assets/1037386/21155528/555e1a20-c127-11e6-8af5-4c833ebf46a5.png">

**Comment by vkoppaka** [comment]
I see the add-in being called "Dumb addin" when installed from the link above as well.

**Comment by lextm** [comment]
The addin web site has experienced some issues recently. Unless Xamarin/Mono guys fix that, I won't be able to provide any guidance.

**Comment by jukafah** [comment]
The 6.0 links are 404'ing: http://addins.monodevelop.com/Project/Index/220

**Comment by lextm** [comment]
Xamarin has just fixed the back end services, so now you can download the latest addin from http://addins.monodevelop.com/Project/Index/220

I just tested and it should now serve the correct build.
