### ISSUE TITLE
Project templates are not available

### ISSUE THREAD

**Issue by b-straub** [xunit/xamarinstudio.xunit#54]
As far I understand the XUnit addin will install project and file templates as well.
Neither on XS 6.2 nor on VS Mac Preview 3 the XUnit Library project will be available.

<img width="404" alt="vsm_xs_xunit" src="https://cloud.githubusercontent.com/assets/7459002/23249207/642dd766-f9a3-11e6-8576-ca17b4a1ea74.png">

**Comment by lextm** [comment]
Xamarin has changed the NUnit templates, so I now edit the xUnit templates accordingly. New releases would be pushed to repo feeds soon.
