### ISSUE TITLE
No support for Nuget v3 Api

### ISSUE THREAD

**Issue by b-straub** [xunit/xamarinstudio.xunit#55]
When adding the XUnit package using the most recent Nuget API (v3), support started with XS 6.1
[NuGetSupportInXamarinStudio6.1](http://lastexitcode.com/blog/2016/09/17/NuGetSupportInXamarinStudio6-1/), the XUnit tests will not be recognized.

XUnitProjectTestSuite.CreateTest just scans for XUnit references in the project file but should also scan the project.json. The project file itself will not not contain any package references anymore when using the Nuget v3 Api therefore there will be no XUnit reference that can be resolved by the XUnitProjectTestSuite.XUnitVersion function.

**Comment by lextm** [comment]
I will do some investigation but generally speaking `project.json` is not going to be supported so I don't expect it to be work.

**Comment by b-straub** [comment]
It's working pretty well:
Use XS 6.2 and create a PCL with a test class and add Xuint 2.1.0 using the Nuget V3 datasource.
A project.json will be created automatically.
Test panel will not show any tests.
Unload the project and add manually a reference to Xunit in the project file. Reload and tests will appear now and can be executed.

Using Xunit 2.2.0 didn't work for me as well as using a netstandard library instead of the PCL.

It's important not to be confused between project.json managing Nuget packages in a new way and project.json as a build template for .Net Core. With VS 2017 things will change again and likely XS, VS Mac as well.

**Comment by lextm** [comment]
I think this issue is more complex than the description. xUnit.net 2.2 release introduces many breaking changes which can affect this extension. I won't be able to address this any time soon.

Appreciated if anyone in the user community can step up.

**Comment by b-straub** [comment]
I implemented the needed support. 

Note: VS Mac also supports the new VS 2017 .NetCore project format, extending the unit reference detection to this format will be easy but currently neither XUnit or this addin are supporting .NETCore projects.

**Comment by lextm** [comment]
Thanks for the PRs. 

Personally I believe the future is MSBuild 15 new schema, where NuGet packages become just like any other references, and `project.json` is gone. Of course, that means we will have to upgrade to xUnit.net 2.2.x, which contains some breaking changes, which I am not yet ready to address.

Let's leave it as it is for a while to see if others have better options.

**Comment by b-straub** [comment]
OK. May be the next month will bring stable Xamarin support for MSBuild 15. Currently XS 6.2 doesn't support it and the VS Mac support is quite incomplete. I will close the request for now.
