### ISSUE TITLE
Can't install on VS for Mac 7.0 build 1566

### ISSUE THREAD

**Issue by tougher** [xunit/xamarinstudio.xunit#59]
It works perfect in the latest Xamarin Studio, but in the latest VS I get this screen when installing from the Extension Manager:
![screen shot 2017-03-15 at 11 52 20](https://cloud.githubusercontent.com/assets/10697/23945250/23831f72-0976-11e7-8a53-92a8ee2ffa2c.png)

There is a lot of changes in the latest VS build.

**Comment by lextm** [comment]
Thanks for the feedback. AddinMaker has just been updated so I will take a look.

**Comment by lextm** [comment]
It seems to install fine now in latest preview builds, though still suffers #60.
