### ISSUE TITLE
Tests not found with VS for Mac Preview 5

### ISSUE THREAD

**Issue by guardrex** [xunit/xamarinstudio.xunit#60]
![testfailure](https://cloud.githubusercontent.com/assets/1622880/24013360/2226b25e-0a4f-11e7-9f57-0cb74b38c473.png)

In spite of everything looking good for xUnit tests in VS for Mac Preview 5 (current release), when I try to run them with the IDE, it throws "Test discovery failed." If I run from Terminal, the test runs fine.

For the failure using the IDE, is this a known issue?

**Comment by lextm** [comment]
Related to #59 

I just found a few underlying changes made in the common unit test base classes, which requires significant changes and testing in this addin. Thus, won't be a quick fix.

**Comment by guardrex** [comment]
@lextm Fair enough ... still preview. I'll just have the tutorial continue to say that they should use the Terminal to run them. I'll track on this issue. When it gets fixed, I'll update the doc. Thanks for your help.

**Comment by guardrex** [comment]
@lextm Just want to add one more related note here: Because the test runner fails, you can't use the Play button or the *Start ...* from the *Run* menu when a test project is present in the solution. It tries to run the tests.

I tried to stop it with a `FactAttribute` that sets a `Skip` on my two test methods, and I also tried to use compiler directives to disable the test methods. Those two approaches failed. :cry: However, I can get the console app to run if I right-click the console app project and select *Run item*. It will only run the one project that way with the referenced class lib project and not try to run the test project.

I have a feeling that this will all go away once tests are running from the VS for Mac UI. Just thought I'd add this tidbit in case someone else lands here looking for a workaround.

**Comment by EltonGarcia** [comment]
Facing the same problem! :/

**Comment by lextm** [comment]
xUnit.net based .NET Core testing can run properly without this extension. So I think probably it is time for Xamarin/Microsoft to take over the responsibility.

**Comment by lextm** [comment]
Shipped 0.7.3 release to address the general usage,

https://github.com/xunit/xamarinstudio.xunit/releases/tag/v0.7.3

However, this build disables the remote unit test runner, so it might lead to other issues.

Another release would be shipped once #61 is fixed.
