### ISSUE TITLE
Test debug doesn't work for xUnit.net 2.3.0 beta 1 (.NET Core)

### ISSUE THREAD

**Issue by azinoviev** [xunit/xamarinstudio.xunit#62]
Visual Studio for Mac (release, but the same actual for previous betas)
.NET Core 1.1.1
XUnit 2.3.0-beta1-build3642
xamarinstudio.xunit 0.7.2 and 0.7.5

Tests run fine, but when I try to debug any test I see debug screen layout for a second and then it stops debug process without any messages. Application output doesn't show any errors (only a lot of "Loaded '...'" messages).

**Comment by lextm** [comment]
So far I think xUnit.net 2.2.0 is the only supported version. <2.2.0 is no longer supported due to the runner binding to 2.2.0.

You are using xUnit.net 2.3.0 beta1, so I am not sure what might happen. Can you roll back to 2.2.0? Any specific reason to use 2.3.0?

**Comment by azinoviev** [comment]
Unf. with version 2.2.0 plugin unable to discover any test.

**Comment by lextm** [comment]
Are you working on a .NET Core console app as Microsoft suggests? Then #63 is already known.

**Comment by azinoviev** [comment]
Yep, .NET Core App. I used 2.3.0 beta1 because test discovery works with it.

**Comment by lextm** [comment]
http://xunit.github.io/docs/getting-started-dotnet-core

Overall, .NET Core test projects (1.x) are processed by Visual Studio for Mac, not this extension. I guess it uses `dotnet test` related infrastructure。

xUnit.net 2.3 seems to implement a new approach (dotnet xunit), which does not fall under `dotnet test`. Thus, Visual Studio for Mac cannot work with that yet. I don't plan to update this extension to support .NET Core in the near future, as it requires a little bit more changes. Maybe it is time to ping Microsoft/Xamarin.

**Comment by lextm** [comment]
Stop .NET Core investigation as it would be handled by Visual Studio for Mac.
