### ISSUE TITLE
[Visual Studio for Mac] Install from file required

### ISSUE THREAD

**Issue by jj09** [xunit/xamarinstudio.xunit#65]
Currently, in order to make this plugin work in VS for Mac you need to manually download extension from https://github.com/xunit/xamarinstudio.xunit/releases and then 'install from file...'

Are there plans to make it working by installing from 'extensions directly'?

**Comment by lextm** [comment]
At this very moment, VS for Mac extension site is not as stable as it can be. Thus, we have the file available at GitHub for manual installation. Meanwhile, you can check the version in Extension Manager to see whether it is the latest.
