### ISSUE TITLE
Visual Studio for Mac does not detect my Tests

### ISSUE THREAD

**Issue by Jonas1197** [xunit/xamarinstudio.xunit#66]
I have added xUnit as an extension and restarted the IDE. I have created a new xUnit Test project in my solution and wrote some code. Afterwards I went to [Run >> Run unit Tests] but this option appears to be grayed-out and I cannot click it. Does VS for Mac support yet xUnit?

Thanks in advance.

**Comment by lextm** [comment]
Try to manually install release 0.7.6,

https://github.com/xunit/xamarinstudio.xunit/releases/tag/v0.7.6

A nasty bug has been fixed and it should work fine now.

**Comment by Jonas1197** [comment]
@lextm Thank you very much, the issue has been fixed! 👍
