### ISSUE TITLE
Unable to install xUnit.net 2.0.0 package for F# project in Monodevelop/.NET 4.0

### ISSUE THREAD

**Issue by jacqueline-homan** [xunit/xamarinstudio.xunit#7]
I am working through a Pluralsight tutorial for F# on Testing. I am on a Linux (Ubuntu) computer and using Monodevelop. I get an error message that says " Could not install package 'xunit.extensibility.core 2.0.0.' You are trying to install this package into a project that targets '.NET framework, Version=4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

**Comment by bradwilson** [comment]
xUnit.net 2.0 requires .NET 4.5 or later.

![](http://i.imgur.com/wtMyAYC.png)

**Comment by jacqueline-homan** [comment]
Brilliant :) I changed my project's options to Mono/.NET 4.5, closes and repopened my solution and then installed xUnit.net which installed perfectly.
