### ISSUE TITLE
Test pad breaks after exceeding 9 test methods (facts)

### ISSUE THREAD

**Issue by Dids** [xunit/xamarinstudio.xunit#70]
Unit test project is using .NET Core 2.0 (2.0.0-preview2-25407-01) and the following packages:  
```
<PackageReference Include="xunit" Version="2.2.0" />
<PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.5.0-preview-20170727-01" />
```

Test pad with 9 test methods:  
![Working with 9 methods](https://www.dropbox.com/s/21gcyoudqzbnv2v/Screenshot%202017-08-05%2012.20.01.png?dl=1 "Working with 9 methods")

Test pad with 10 test methods:  
![Broken with 10 methods](https://www.dropbox.com/s/wabkcq3cr0kerpu/Screenshot%202017-08-05%2012.21.18.png?dl=1 "Broken with 10 methods")

**Comment by Dids** [comment]
Running the tests manually (ie `dotnet test`) works fine, so to me it looks like a bug in the extension.

**Comment by Dids** [comment]
Additionally, if I click the circle next to the test method (in the IDE), then hit run/debug, it only builds the project and doesn't actually run it/test it.

**Comment by lextm** [comment]
You can uninstall this extension to verify. .NET Core projects do not rely on this extension, and issues like this should be reported to Microsoft/Xamarin.

**Comment by Dids** [comment]
You are correct, thank you & apologies, I'll forward it to Microsoft. :)
