### ISSUE TITLE
Add an option to run xunit tests in x64 environment?

### ISSUE THREAD

**Issue by Dorokhov** [xunit/xamarinstudio.xunit#71]
Can I run xunit tests in x64 environment?

**Comment by lextm** [comment]
Not quite sure how to provide x86/x64 switch yet. Will investigate.

**Comment by lextm** [comment]
https://github.com/xunit/xamarinstudio.xunit/releases/tag/v0.7.9

0.7.9 release forces the runner to run as x64. Will further explore the opportunity to provide IDE based switch between x64 and x86.

**Comment by lextm** [comment]
https://github.com/xunit/xamarinstudio.xunit/releases/tag/v0.7.10 introduces `.runsettings` support to match Visual Studio convention.
