### ISSUE TITLE
Test shows as exception in Test Explorer

### ISSUE THREAD

**Issue by ghost** [xunit/xamarinstudio.xunit#73]
**Environment**
- [ ] Extension version: 0.7.12
- [ ] Visual Studio for Mac version: 7.1.5 (build 2)
- [ ] Operating System version: macOS Sierra 10.12.4
- [ ] xUnit.net assembly version: xUnit 2.2.0

**Expected behavior**
Test show up in the test explorer

**Actual behavior**
Tests don't show up in the test explorer

**Detailed Steps to reproduce the problem**
Not really steps but more info about the exception shown in the explorer.
![screen shot 2017-09-29 at 13 24 43](https://user-images.githubusercontent.com/9677292/31014219-0f28e09e-a51a-11e7-9e46-5ec750808f3c.png)

Aside from that I did add the environment variable and set it to false.

**Comment by lextm** [comment]
Can you provide a sample project to reproduce this issue stably? You can upload directly to this issue via GitHub if that's not confidential, or send to my mailbox at support@lextm.com if you want to keep it private.

**Comment by michaelgobbers** [comment]
We cannot provide you with a sample project but is there any way we can get you more logging information?

**Comment by michaelgobbers** [comment]
[Ide.2017-10-13__16-05-46.log](https://github.com/xunit/xamarinstudio.xunit/files/1382917/Ide.2017-10-13__16-05-46.log)

These are some ide logs that contain the remoteprocessexception

**Comment by lextm** [comment]
@michaelgobbers Based on the log, a sample project is surely required. 

The call stack does not contain enough information on the culprit.

I have no plan to add more logging, as it would make things complicated. You would have to do some debugging on your own.

**Comment by lextm** [comment]
Please read #77 for more details.
