### ISSUE TITLE
Test shows as exception in Test Explorer after install and enabling xUnit nuget package in visual studio for mac in xamarin.forms application, Unit Test window is coming blank

### ISSUE THREAD

**Issue by RiteshRana10** [xunit/xamarinstudio.xunit#74]
**Running .NET Core based unit test projects in Visual Studio for Mac does not require this extension.**
This extension is only needed if you want to run Mono based unit test projects. 
Thus, don't report .NET Core based issues to this repo.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [ ] Extension version:
- [ ] Visual Studio for Mac version:
- [ ] Operating System version:
- [ ] xUnit.net assembly version:

**Expected behavior**

**Actual behavior**

**Detailed Steps to reproduce the problem**

**Comment by lextm** [comment]
If you provide no information at all, no investigation would be given to this issue.

**Comment by RiteshRana10** [comment]
![image](https://user-images.githubusercontent.com/8260631/31369494-92ab489a-ada2-11e7-9404-48a95abf0753.png)
![screen shot 2017-10-10 at 9 58 27 am](https://user-images.githubusercontent.com/8260631/31369503-a1886384-ada2-11e7-9158-6b76782eeb44.jpg)
 i am seeing these exceptions instead of name of the Unit test cases after writing unit test cases using xUnit in Visual studio for mac Xamarin.forms Application

**Comment by RiteshRana10** [comment]
These exceptions are shown in Unit Test case window in visual studio for mac, and if i am using nUnit test caes for same project its working perfectly fine, so my question is should i use nUnit for wirting unit test cases for xamarin forms or is it possible to do it using xUnit framework in visual studio for mac

**Comment by lextm** [comment]
When you open a new issue here, I already provided a template for you to fill in all necessary details, but you don't. So merely the screen shots and short descriptions are almost useless.

Like I said, if you do want this issue to be addressed, provide more information.

Besides, if you happen to use xUnit.net 2.3, then any issue can happen, due to #75 .

**Comment by lextm** [comment]
Please read #77 for more details.
