### ISSUE TITLE
Crashing VS for Mac

### ISSUE THREAD

**Issue by BrennanConroy** [xunit/xamarinstudio.xunit#76]
This extension can crash VS for Mac on the following line:
https://github.com/xunit/xamarinstudio.xunit/blob/de98a27095fcd4aba0a684aa6e196b91158151b0/MonoDevelop.XUnit/MonoDevelop.UnitTesting.XUnit/SystemTestProvider.cs#L107
If you get a `(403) Forbidden` from the Rollbar API then you throw and cause a fatal error in VS for Mac.

**Comment by lextm** [comment]
https://github.com/xunit/xamarinstudio.xunit/releases/tag/v0.7.12

You might disable reporting via the environment variable mentioned above.

**Comment by therealjohn** [comment]
I've run into this issue to. @lextm what might I be missing? 

```
Johns-MacBook-Pro-2:~ john$ env
MONODEVELOP_XUNIT_ROLLBAR_ENABLED=FALSE
... (other environment variables, snipped for brevity)
```

**Comment by therealjohn** [comment]
Doh, never mind. I misunderstood [how to set an env var on macOS](https://apple.stackexchange.com/a/106814). With it properly disabled, I've worked around the crash.

**Comment by lextm** [comment]
You should upgrade to [0.7.15 release](https://github.com/xunit/xamarinstudio.xunit/releases/tag/v0.7.15).
