### ISSUE TITLE
Enable ability to stop debugging

### ISSUE THREAD

**Issue by jchannon** [xunit/xamarinstudio.xunit#9]
Once I debug a test and maybe half way through see a problem and want to cancel debugging clicking the stop button in Xamarin Studio doesn't do anything and sometimes I have to close Xamarin and reopen due to the nature of the test.

**Comment by lextm** [comment]
Confirmed that it is a critical issue.

**Comment by lextm** [comment]
Initial investigation indicates that for 0.5.x of this add-in, some required interface is not yet fully implemented (XUnitExecutionSession does not implement ITestProgressMonitor). That prevents cancellation from UI to the related code.

It would be difficult to resolve such issues for 0.5.x, as the related interfaces also change in MonoDevelop/Xamarin Studio 6.0, and we will focus more on 0.6.0 builds.

Will provide more updates once we get debugging support on 0.6.0.

**Comment by lextm** [comment]
The initial investigation went on the wrong direction.

By disabling the remoting helper in `XUnitTestExecutor.Run`, I can see that cancellation works fine. So it seems that passing `executionListener` (along with the cancellation token) across the process boundary has led to the issue.

Need to further investigate on how to properly handle that.

**Comment by lextm** [comment]
The fix is included in 0.6.3.
